accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('signup/', views.signupView, name='signup'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
]

urlpatterns += staticfiles_urlpatterns()

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path(r'<slug:slug>/$', views.blogView, name='blog'),
    path('new-blog/', views.createBlogView, name='createBlog'),
    path(r'edit-blog/<slug:slug>', views.editBlogView, name='editBlog'),
    path(r'delete-blog/<slug:slug>', views.deleteBlogView, name='deleteBlog'),
    # path(r'blog/delete/<slug:slug>', views.deleteConfirm, name='delete'),
    path(r'like/<slug:slug>', views.likeBlog, name='blog_like')
]

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
# from django.db.models.signals import pre_save
# from django.utils.text import slugify

class Blog(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='blog_like')

    def likeCount(self):
        return self.likes.count()

    def __str__(self) -> str:
        return self.title

    def trimLength(self):
        return self.body[:20] + '...'






# def create_slug(instance, new_slug=None):
#     slug = slugify(instance.title)
#     if new_slug == None:
#         new_slug = slug

#     qs = Blog.objects.filter(slug=slug).order_by("-id")
#     qs_exists = qs.exists();
#     if qs_exists:
#         new_slug = "%s-%s" %(slug, qs.first.id())
#         return create_slug(instance, new_slug)
#     return slug


# def pre_save_blog_reciever(sender, instance, args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug(instance)

# def pre_save_blog(sender, instance, args, **kwargs):
#     slug = slugify(instance.title)
#     instance.slug = slug


# pre_save.connect(pre_save_blog, sender=Blog)
    
    

core/forms.py
from django import forms
from . import models

class createBlog(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'body']

accounts/views.py
from django.http import HttpResponse, request
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


def loginView(request):
    if request.method == 'POST':
        loginForm = AuthenticationForm(data = request.POST)
        if loginForm.is_valid():
            user = loginForm.get_user()
            login(request, user)
            return redirect('core:home')
    else:
        loginForm = AuthenticationForm(request.POST)
    return render(request, 'accounts/login.html', {'loginForm': loginForm})


@login_required
def logoutView(request):
    logout(request)
    return redirect('accounts:login')



def signupView(request):
    if request.method == 'POST':
        signupForm = UserCreationForm(request.POST)
        if signupForm.is_valid():
            user = signupForm.save()
            print(user)
            login(request, user)
            return redirect('core:home')
    else:
        signupForm = UserCreationForm()
        return render(request, 'accounts/signup.html', {'signupForm': signupForm})

core/views.py
from django.core.checks import messages
from core.models import Blog
from django.contrib import messages
from django.contrib.auth.decorators import login_required 
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.text import slugify
import string
import random
from . import models, forms

def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))

def home(request):
    blogs = models.Blog.objects.all().order_by('date')
    return render(request, 'core/home.html', {'blogs': blogs})


@login_required 
def blogView(request, slug):
    blog = models.Blog.objects.get(slug = slug)
    likeCount = blog.likeCount()

    liked = False
    if blog.likes.filter(id = request.user.id).exists():
        liked = True

    context = {
        'blog': blog,
        'likeCount': likeCount,
        'liked': liked
    }
    return render(request, 'core/blog.html', context)

@login_required
def createBlogView(request):
    if request.method == 'POST':
        print('post request')
        form = forms.createBlog(request.POST)
        if form.is_valid():
            savedFormObject = form.save(commit=False)
            savedFormObject.author = request.user
            savedFormObject.slug = slugify(savedFormObject.title + "-" + rand_slug())
            savedFormObject.save()
        return redirect('/')
    else:
        createBlogForm = forms.createBlog()
    return render(request, 'core/createBlog.html', {'form': createBlogForm} )

@login_required
def editBlogView(request, slug):
    formData = get_object_or_404(Blog, slug=slug)
    author_id = formData.author.id
    blog = Blog.objects.get(slug=slug)
    form = forms.createBlog(instance=blog)

    if request.method == 'POST':
        updateBlogFormData = forms.createBlog(request.POST, instance=blog)
        if updateBlogFormData.is_valid():
            savedFormObject = form.save(commit=False)
            savedFormObject.slug = slugify(savedFormObject.title + "-" + rand_slug())
            savedFormObject.save()
        messages.success(request, 'blog updated')
        return redirect('/') 

    
    context ={
        'form': form,
        'author_id': author_id
    }
    return render(request, 'core/editBlog.html', context )
 



@login_required
def deleteBlogView(request, slug):
    blog = Blog.objects.get(slug=slug)
    context ={
        'blog':blog
    }

    return render(request, 'core/deleteBlog.html', context)

# @login_required
# def deleteConfirm(request, slug):
#     blog = get_object_or_404(Blog, slug=slug)
#     if request.method == 'POST':
#         blog.delete()
#         redirect('/')




def likeBlog(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    liked = False
    if blog.likes.filter(id = request.user.id).exists():
        blog.likes.remove(request.user)
        liked = False

    else:
        blog.likes.add(request.user)
        liked = True

    
    return redirect('core:blog', slug=slug)

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}

{% include "components/navbar.html" %}

<div class="container">
    <form method="POST" >
        <div class="container lighten-2">
            <div class="row col s12 md4">
                <div class="container">
                    {% csrf_token %}
                    {{loginForm}}
                    <button type="submit" class="btn waves-effect waves-ligh">Login</button>
                </div>
            </div>
        </div>

    </form>
</div>

{% endblock content %}

templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}

{% include "components/navbar.html" %}

<div class="container">
    <form method="POST" >
        <div class="container lighten-2">
            <div class="row col s12 md4">
                <div class="container">
                    {% csrf_token %}
                    {{signupForm}}
                    <button type="submit" class="btn waves-effect waves-ligh">Login</button>
                </div>
            </div>
        </div>

    </form>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogger</title>

    <!-- css links -->
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        

</head>
<body>
    
    {% block content %} {% endblock content %}

</body>
</html>

templates/components/navbar.html
{% extends "base.html" %}
{% block content %}

<nav>
    <div class="nav-wrapper">
      <a href="{% url 'core:home' %}" class="brand-logo">Blogger</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">

        {% if user.is_authenticated %}
        <li>{{user.username}}</li>
        <li><a href="{% url 'core:createBlog' %}">New Blog</a></li>
        <li><a href="{% url 'accounts:logout' %}">logout</a></li>
        
        {% else %}
        <li><a href="{% url 'accounts:login' %}">login</a></li>
        <li><a href="{% url 'accounts:signup' %}">signup</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

{% endblock content %}

templates/core/blog.html
{% extends "base.html" %}
{% block content %}

{% include "components/navbar.html" %}

<div class="container">
    <div class="title">
        <h2>{{blog.title}}</h2>
    </div>

    <div class="blog-body">
        <p>{{blog.body}}</p>
    </div>

    <div class="author">
        {{blog.author}}
    </div>
    <div class="date-created">
        <h6>
            Created on: {{blog.date}}
        </h6>
    </div> 
    

    {% if user.id == blog.author.id %}
        <div class="edit_blog">
            <a href="{% url 'core:editBlog' slug=blog.slug %}"><button>Edit</button></a>
        </div>

        <div class="edit_blog">
            <a href="#"><button>delete</button></a>
        </div>

    {% endif %}


    <br><br>
    <hr>
    <br>
    <form action="{% url 'core:blog_like' slug=blog.slug %}" method="POST">
        {% csrf_token %}
        {% if liked %}
            <button type="submit" value="{{blog.id}}" name="blog_id" class='btn btn-primary btn-sm'>Unlike</button>
        {% else %}
            <button type="submit" value="{{blog.id}}" name="blog_id" class='btn btn-primary btn-sm'>Like</button>
        {% endif %}
    </form>
    {{likeCount}} Likes
</div>

{% endblock content %}

templates/core/createBlog.html
{% extends "base.html" %}
{% block content %}

{% include "components/navbar.html" %}

    <div class="container">
        <h2>Create blog page</h2>
        <form method="post" class="">
            {% csrf_token %}
            <label for="title"> Title </label>
            {{form.title}}

            <label for="body">Body </label>
            {{form.body}}
            <input type="submit" value="Create" style="margin-top:30px">
        </form>
    </div>

{% endblock content %}

templates/core/deleteBlog.html
{% extends "base.html" %}
{% block content %}

{% include "components/navbar.html" %}

<div class="container">
    <div class="title">
        <h2>{{blog.title}}</h2>
    </div>
    <div class="confirm-form">
        <h46Are you sure ?</h6>
            <form method="POST">
                {% csrf_token %}
                <a href="{% url 'core:delete' slug=blog.slug %}">
                    <button type="submit">Delete</button>
                </a>
            </form>
    </div>
</div>

{% endblock content %}

templates/core/editblog.html
{% extends "base.html" %}
{% block content %}

{% include "components/navbar.html" %}


<div class="container">

    {% if user.id == author_id %}
        <h2>Create blog page</h2>
        <form method="post" class="">
            {% csrf_token %}
            <label for="title"> Title </label>
            {{form.title}}
            <label for="body">Body </label>
            {{form.body}}
            <input type="submit" value="Update" style="margin-top:30px">
        </form>
    {% else %}  
        <h3 class="center"> Error 404: Page not found </h3>
    {% endif %}

</div>

{% endblock content %}

templates/core/home.html
{% extends "base.html" %}
{% block content %}

{% include "components/navbar.html" %}

<div class="container">
    <h1>Trending Blogs</h1>
    {% for blog in blogs %}
    <ul>
         <li>
           <a href="{% url 'core:blog' slug=blog.slug %}"> {{blog.title}} </a>
        </li>
         <li>
            {{blog.trimLength}}
        </li>
    </ul>
    {% endfor %}
    
</div>

{% endblock content %}